# Generated by Django 4.0.2 on 2022-03-07 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipoDocumentos', '0001_initial'),
        ('donantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donantes',
            name='tipoDNI',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipoDocumentos.tipodocumento'),
        ),
    ]
