# Generated by Django 4.0.2 on 2022-03-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sexo', '0001_initial'),
        ('donantes', '0002_alter_donantes_tipodni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donantes',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sexo.sexo'),
        ),
    ]
