# Generated by Django 4.0.2 on 2022-03-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gruposFactor', '0001_initial'),
        ('ciudades', '0001_initial'),
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('tipoDNI', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=255)),
                ('fechaNacimiento', models.DateField()),
                ('fechaLimite', models.DateField()),
                ('cantidadDonantes', models.IntegerField()),
                ('mail', models.CharField(max_length=255)),
                ('comentario', models.TextField(max_length=1024)),
                ('completo', models.BooleanField(default=False)),
                ('telefono', models.CharField(max_length=255)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ciudades.ciudad')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instituciones.institucion')),
                ('tipoSangre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gruposFactor.grupofactor')),
            ],
        ),
    ]
