# Generated by Django 4.0.2 on 2022-03-18 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudades_ciudad',
        ),
    ]
