# Generated by Django 4.0.2 on 2022-03-18 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciudades', '0002_alter_ciudad_options_alter_ciudad_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ciudad',
            table='ciudad',
        ),
    ]
