# Generated by Django 4.0.2 on 2022-03-07 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('donantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReposicionesAsignadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaReposicionElegida', models.DateField()),
                ('comentario', models.TextField(max_length=1024)),
                ('idDonante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='donantes.donantes')),
                ('idPaciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.pacientes')),
            ],
        ),
    ]
